modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/creatif"
logoFile="images/icon.png" 
#credits="" #optional
authors="${mod_authors}"
#displayTest="MATCH_VERSION" # if nothing is specified, MATCH_VERSION is the default when clientSideOnly=false, otherwise IGNORE_ALL_VERSION when clientSideOnly=true (#optional)

description='''${mod_description}'''

[[dependencies.${mod_id}]] 
    modId="forge" 
    mandatory=true 
    versionRange="${forge_version_range}" 
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.8,6.1.0)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="emi"
    mandatory=false
    versionRange="[1.0.0,1.2.0)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[15.19.0,16.0.0)"
    ordering="NONE"
    side="CLIENT"
